# Generated by Django 3.2.5 on 2021-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('nova_groups', models.PositiveSmallIntegerField()),
                ('nutrition_grades', models.CharField(max_length=1)),
                ('stores', models.CharField(max_length=100)),
                ('eco_score', models.CharField(max_length=1)),
                ('picture', models.URLField()),
            ],
        ),
    ]
