# Generated by Django 3.2.5 on 2021-08-13 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0012_auto_20210813_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_product', to='catalogue.product')),
                ('substitute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitude_product', to='catalogue.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favorite_product',
            constraint=models.UniqueConstraint(fields=('product', 'substitute'), name='favorite_unique'),
        ),
    ]
