# Generated by Django 3.2.5 on 2021-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_alter_favorite_product_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite_product',
            name='favorite_unique',
        ),
        migrations.AddConstraint(
            model_name='favorite_product',
            constraint=models.UniqueConstraint(fields=('product', 'substitute', 'user'), name='favorite_unique'),
        ),
    ]
