# Generated by Django 3.2.5 on 2021-08-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_product_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='picture_url',
        ),
    ]
