# Generated by Django 3.2.5 on 2021-08-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_alter_product_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'produit'},
        ),
    ]
